### PR TITLE
Iss 113

### LINKED ISSUE #113: Reintrocude previously unused theme parameters
* #' @param lwd_ticks_1 numeric width of type 1 ticks, defaults to 1.5.
* #' @param lwd_ticks_2 numeric width of type 1 ticks, defaults to 1.
* #' @param tcl_quarterly_tick_tcl numeric, same as base \code{\link{plot}} tcl parameter defaults to -.5,
* #' @param subtitle_cex.main numeric same as base \code{\link{plot}} parameter, defaults to 1

### PR DESCRIPTION
**Pull request by HomoCodens**
Closes #113

### CODE REVIEW

**Comment by mbannert** [comment]
Hmm, why do you prefer fraction of plotting region over fraction of line. I played around with this and I feel that the latter maybe a bit more stable / predictable....

**Comment by HomoCodens** [comment]
No particular reason. If tcl is more stable we can switch back to that.

**Comment by mbannert** [comment]
Let's do that, but I fully agree with you on not having both params. Do we just have to discard this PR ? Doesn't it contain other cleanups in terms of throwing out unused params?

**Comment by HomoCodens** [comment]
It also reintroduces `subtitle_cex` and the length parameter for subticks.
Changing to `tcl` is no biggie though.

**Pull request merged**
