### PR TITLE
Dummy ts generator

### PR DESCRIPTION
**Pull request by HomoCodens**
Fun stuff!

```R
tsplot(generate_random_ts())

tsplot(generate_random_ts(n = 3, ranges_min = 0, ranges_max = c(3, 5, 10), ts_names = c("Bananas", "Cupcakes", "Strarberries")))

tsplot(generate_random_ts(random_NAs = TRUE))

tsplot(generate_random_ts(frequency_shifts  = TRUE), theme = init_tsplot_theme(show_points = TRUE))
```

### CODE REVIEW

**Comment by HomoCodens** [comment]
Righto.

We could change dev to the default branch:
https://help.github.com/articles/setting-the-default-branch/

But I'm not sure if this makes dev the new "master" with protection and all. Well, need to pay more attention when creating PRs.

**Comment by HomoCodens** [comment]
Options for future consideration:

* Trends (linear, exponential)
* Cyclic patterns

For purposes of testing `tsplot` these are not needed of course so not urgent/vital.

**Comment by mbannert** [comment]
`frequencies` parameter should be `frequency` unless a vector is allowed for different series when n > 1. 
That would be a neat feature. Also it would make it more explicit in the documentation that uniform is the default. 

instead of sayin if normally_distributed == TRUE I would rather say: ignored unless normally_distributed is set to TRUE.

**Comment by mbannert** [comment]
in that case it's only the documentation which needs a change...

btw:  I don't think we should make dev the default branch. I read about this option a long while ago and also thought this just makes dev the new master in terms of blocking etc. I never really tried it though. Maybe we can try with a dummy repository, but that being said, I am also happy with the way it is right now.

**Pull request merged**
